export const categories = [
  { id: 'command', label: 'Command & visibility', icon: 'grid', accent: 'violet' },
  { id: 'intelligence', label: 'Intelligence & conversation', icon: 'brain', accent: 'blue' },
  { id: 'assets', label: 'Assets & data', icon: 'layers', accent: 'cyan' },
  { id: 'connections', label: 'Connections & trust', icon: 'nodes', accent: 'green' },
  { id: 'workflow', label: 'Workflow & automation', icon: 'check', accent: 'amber' },
  { id: 'reliability', label: 'Reliability & quality', icon: 'activity', accent: 'rose' },
  { id: 'experience', label: 'Accessibility & experience', icon: 'sparkles', accent: 'violet' },
];

const rows = [
  ['command', 'Unified command overview', 'One landing view for status, local assets, tasks, and available modules.'],
  ['command', 'Department-aware navigation', 'Each destination names its purpose so icons never stand alone.'],
  ['command', 'Workspace-wide search', 'Search the feature registry, tasks, providers, and locally stored asset names.'],
  ['command', 'Keyboard command palette', 'Open navigation and search with Ctrl/⌘ K.'],
  ['command', 'Local-mode status banner', 'Clearly distinguishes this browser build from live production services.'],
  ['command', 'Live local clock', 'Shows the current time in the device locale.'],
  ['command', 'Freshness timestamps', 'Every runtime check records when it was last made.'],
  ['command', 'Service-health summary', 'Reports the actual local HTTP health endpoint and unavailable integrations.'],
  ['command', 'Alert and notice center', 'Review local events, setup notes, and actionable attention items.'],
  ['command', 'One-action refresh', 'Rechecks the local runtime without implying remote service health.'],
  ['command', 'Responsive command layout', 'Reflows navigation, metrics, and panels for narrow screens.'],

  ['intelligence', 'Local guided assistant', 'Answers common questions from the installed registry and this browser’s state.'],
  ['intelligence', 'Intent-based routing', 'Recognizes questions about features, assets, activity, and connections.'],
  ['intelligence', 'Persistent conversation', 'Keeps the local chat history in this browser until you clear it.'],
  ['intelligence', 'Suggested prompts', 'One-tap prompts cover status, innovation progress, and next actions.'],
  ['intelligence', 'Visible conversation states', 'Shows listening, understanding, planning, and reporting in the chat flow.'],
  ['intelligence', 'Evidence-aware answers', 'Assistant replies identify which local panel or registry informed the response.'],
  ['intelligence', 'Actionable next steps', 'Recommendations link to a real destination or explain what setup is required.'],
  ['intelligence', 'Copy assistant response', 'Copy a response to the clipboard with a visible success message.'],
  ['intelligence', 'Export conversation', 'Download the local transcript as a text file.'],
  ['intelligence', 'Voice dictation input', 'Use browser speech recognition when the browser offers it and you start it.'],
  ['intelligence', 'Spoken responses', 'Read a local assistant response aloud with the browser speech engine.'],
  ['intelligence', 'Offline assistant fallback', 'Keeps basic guidance available without a network or model connection.'],

  ['assets', 'Browser-local asset vault', 'Store selected file bytes in IndexedDB on this device; nothing is uploaded.'],
  ['assets', 'Asset metadata index', 'Track file name, format, size, date added, and checksum.'],
  ['assets', 'SHA-256 fingerprints', 'Calculate a browser-side checksum for each added file.'],
  ['assets', 'Download integrity verification', 'Recalculate each file checksum before download and stop if the stored bytes do not match.'],
  ['assets', 'Duplicate detection', 'Warn when the same file fingerprint is already in this local vault.'],
  ['assets', 'Asset search and filters', 'Filter by name, type, active state, or recently deleted state.'],
  ['assets', 'Sortable asset inventory', 'Sort the asset table by name, date, or file size.'],
  ['assets', 'Asset downloads', 'Download the original file from the same browser that stored it.'],
  ['assets', 'Recoverable asset removal', 'Move files to a local trash view and restore them when needed.'],
  ['assets', 'Registry export', 'Export asset metadata to JSON or CSV for review.'],
  ['assets', 'Local-only storage notice', 'Show the device and browser boundary next to file controls.'],
  ['assets', 'Asset activity history', 'Record file additions, duplicate checks, downloads, and restores locally.'],

  ['connections', 'Provider status directory', 'See the connection state for Drive, Microsoft, Dropbox, GitHub, and the model gateway.'],
  ['connections', 'Connection setup details', 'Open clear setup requirements for each provider instead of a false connect button.'],
  ['connections', 'Disconnected-state recovery', 'Explain what is missing and offer a copyable setup checklist.'],
  ['connections', 'Credential boundary notice', 'Never request or save API keys or provider passwords in the frontend.'],
  ['connections', 'Provider freshness fields', 'Display that no provider heartbeat exists until authorization is configured.'],
  ['connections', 'Local device-bridge status', 'Report that browser Bluetooth and Wi-Fi bridge state is not available here.'],
  ['connections', 'Permission transparency', 'Explain why this browser cannot claim device-level access without a native bridge.'],
  ['connections', 'Least-privilege guidance', 'Remind setup owners to request only provider scopes their workflow needs.'],
  ['connections', 'Approval-aware setup', 'Treat external account authorization as a separate, explicit setup step.'],
  ['connections', 'Connection audit notes', 'Record local setup-review actions without inventing provider events.'],
  ['connections', 'Backend-ready adapter surface', 'Keep provider status panels ready for a future authenticated backend.'],

  ['workflow', 'Local task board', 'Create and track tasks in the Activity workspace.'],
  ['workflow', 'Task priorities', 'Set normal, important, or urgent priority on local tasks.'],
  ['workflow', 'Due-date tracking', 'Add a due date and sort tasks by the date you entered.'],
  ['workflow', 'Task completion controls', 'Mark a task complete or reopen it.'],
  ['workflow', 'Task search and filters', 'Show open, complete, or all tasks and search their titles.'],
  ['workflow', 'Task notes', 'Attach a short working note to each task.'],
  ['workflow', 'Task reminders in the workspace', 'Surface due-soon items in the command center.'],
  ['workflow', 'Quick task creation', 'Create a task from the Activity screen without an external service.'],
  ['workflow', 'Task export', 'Download tasks as a portable JSON file.'],
  ['workflow', 'Activity event stream', 'Review meaningful local changes in time order.'],
  ['workflow', 'Action confirmation feedback', 'Show a toast and activity entry after successful local actions.'],

  ['reliability', 'Health endpoint', 'Serve a real GET /api/health response from the local Node runtime.'],
  ['reliability', 'Offline app shell', 'Cache the main application files for repeat use after the first visit.'],
  ['reliability', 'Network-state feedback', 'Show when the app has lost access to its local runtime endpoint.'],
  ['reliability', 'Structured local diagnostics', 'Separate the frontend build state from external provider state.'],
  ['reliability', 'Input validation', 'Validate task titles, upload types, and imported backup structure.'],
  ['reliability', 'Importable local backup', 'Restore tasks and preferences from a validated JSON export.'],
  ['reliability', 'Schema-versioned preferences', 'Keep browser settings grouped under a versioned storage key.'],
  ['reliability', 'No dependency install required', 'Run with Node built-ins and no third-party runtime packages.'],
  ['reliability', 'Automated smoke tests', 'Check the 77-item registry and the real local health route.'],
  ['reliability', 'No dead-end navigation', 'Every visible navigation item, dialog, filter, and action has a working outcome.'],

  ['experience', 'Dark high-contrast theme', 'Keep labels and control boundaries legible in the violet command palette.'],
  ['experience', 'Compact-density preference', 'Reduce padding for dense data review and persist the choice.'],
  ['experience', 'Reduced-motion support', 'Respect the operating system’s reduced-motion preference.'],
  ['experience', 'Keyboard-accessible navigation', 'Use native buttons, focus styles, and a skip-to-content link.'],
  ['experience', 'Screen-reader state labels', 'Announce status updates and toast messages with live regions.'],
  ['experience', 'Responsive touch controls', 'Keep buttons and menus reachable on phone-sized displays.'],
  ['experience', 'Accessible search dialog', 'Provide an explicit label, escape-to-close, and keyboard-first focus.'],
  ['experience', 'Installable app manifest', 'Offer a browser install path when the runtime supports PWA installation.'],
  ['experience', 'Department descriptions', 'Pair every main navigation icon with its function and destination.'],
  ['experience', 'Clear sample-data labels', 'Mark any illustrative telemetry as sample data in the interface.'],
];

export const innovations = rows.map(([category, title, description], index) => ({
  id: `V-${String(index + 1).padStart(2, '0')}`,
  category,
  title,
  description,
  status: 'Installed in local frontend',
}));
